//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Newcatchy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public System.DateTime Date { get; set; }
        public int Food { get; set; }
        public int Education { get; set; }
        public int Health { get; set; }
        public int Travel { get; set; }
        public int Others { get; set; }
    }
}
